name: Terraform Apply

on:
    push:
      tags:
        - '[0-9].+[0-9].+[0-9]'
    workflow_dispatch: 

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout other repository
        uses: actions/checkout@v2
        with:
          repository: DavoA/TerraformAction
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2
            
      - name: Set Terraform variables
        env:
            url: "https://github.com/DavoA/PythonSimple.git"
        run: |
            echo "TF_VAR_statement=$(basename ${GITHUB_REF})" >> $GITHUB_ENV
            echo "TF_VAR_instance_name=${{ github.sha }}" >> $GITHUB_ENV
            echo "TF_VAR_url=$url" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: |
            terraform init
      
      - name: Apply Terraform changes
        run: terraform apply -auto-approve
