name: Terraform Apply

on:
    push:
      tags:
        - '[0-9].+[0-9].+[0-9]'
    workflow_dispatch: 

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout other repository
        uses: actions/checkout@v2
        with:
          repository: DavoA/TerraformAction
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"

      - name: Set AWS credentials
        env:
          AWS_REGION: "us-east-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV

      - name: Set Terraform variables
        env:
            url: "https://github.com/DavoA/PythonSimple.git"
        run: |
            echo "TF_VAR_statement=$(basename ${GITHUB_REF})" >> $GITHUB_ENV
            echo "TF_VAR_instance_name=${{ github.sha }}" >> $GITHUB_ENV
            echo "TF_VAR_url=$url" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: |
            terraform init
      
      - name: Apply Terraform changes
        run: terraform apply -auto-approve
